# Generated by Django 3.2.3 on 2021-05-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20210522_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
